import React, { useState, useEffect, useRef } from 'react'
import Globe from 'react-globe.gl'
import { motion, AnimatePresence } from 'framer-motion'
import { useTheme } from '../../context/ThemeContext'

interface CulturalMarker {
  id: string
  name: string
  lat: number
  lng: number
  era: 'ancient' | 'modern' | 'future'
  description: string
  stitchType: string
  curvature: number
  color: string
  size: number
}

interface ThaliaGlobeProps {
  era?: 'ancient' | 'modern' | 'future' | 'all'
  onMarkerClick?: (marker: CulturalMarker) => void
  activeMarkerId?: string | null
  showTradeRoutes?: boolean
}

const ThaliaGlobe: React.FC<ThaliaGlobeProps> = ({
  era = 'all',
  onMarkerClick,
  activeMarkerId: _activeMarkerId,
  showTradeRoutes: _showTradeRoutes = true
}) => {
  const { theme } = useTheme()
  const globeRef = useRef<any>(null)
  const [markers, setMarkers] = useState<CulturalMarker[]>([])
  const [selectedMarker, setSelectedMarker] = useState<CulturalMarker | null>(null)
  const [_globeRotation, setGlobeRotation] = useState({ lat: 0, lng: 0 })
  const [isRotating, setIsRotating] = useState(true)
  const [globeSize, setGlobeSize] = useState(600)
  const [isMobile, setIsMobile] = useState(false)
  const [touchStart, setTouchStart] = useState<{x: number, y: number} | null>(null)

  // Cultural markers data
  const culturalMarkers: CulturalMarker[] = [
    {
      id: 'irish_lace',
      name: 'Irish Lace',
      lat: 53.3498,
      lng: -6.2603,
      era: 'ancient',
      description: 'Delicate lacework from 19th century Ireland, known for intricate floral patterns and negative space.',
      stitchType: 'Filet Crochet',
      curvature: -0.3,
      color: '#10B981',
      size: 0.8
    },
    {
      id: 'oya_turkey',
      name: 'Oya Lace',
      lat: 39.9334,
      lng: 32.8597,
      era: 'ancient',
      description: 'Traditional Turkish needle lace with floral motifs, often used as edging on headscarves.',
      stitchType: 'Needle Lace',
      curvature: -0.2,
      color: '#8B5CF6',
      size: 0.7
    },
    {
      id: 'japanese_amigurumi',
      name: 'Amigurumi Core',
      lat: 35.6762,
      lng: 139.6503,
      era: 'modern',
      description: 'Japanese art of crocheting small stuffed toys, using spherical geometry for 3D forms.',
      stitchType: 'Spherical Stitch',
      curvature: 0.5,
      color: '#EF4444',
      size: 1.0
    },
    {
      id: 'peruvian_textiles',
      name: 'Andean Textiles',
      lat: -12.0464,
      lng: -77.0428,
      era: 'ancient',
      description: 'Pre-Columbian textile traditions with geometric patterns and symbolic motifs.',
      stitchType: 'Geometric Weave',
      curvature: -0.1,
      color: '#F59E0B',
      size: 0.9
    },
    {
      id: 'african_basketry',
      name: 'African Basketry',
      lat: -1.2921,
      lng: 36.8219,
      era: 'ancient',
      description: 'Traditional coiled basketry techniques that inspired modern crochet structures.',
      stitchType: 'Coiled Stitch',
      curvature: 0.3,
      color: '#DC2626',
      size: 0.8
    },
    {
      id: 'scandinavian_fairisle',
      name: 'Nordic Fair Isle',
      lat: 60.1282,
      lng: 18.6435,
      era: 'modern',
      description: 'Colorwork knitting techniques adapted to crochet for stranded color patterns.',
      stitchType: 'Colorwork',
      curvature: 0.1,
      color: '#3B82F6',
      size: 0.7
    },
    {
      id: 'cyber_crochet',
      name: 'Cyber Crochet',
      lat: 37.7749,
      lng: -122.4194,
      era: 'future',
      description: 'Algorithmic crochet patterns generated by AI, exploring hyperbolic surfaces.',
      stitchType: 'Hyperbolic Surface',
      curvature: -0.5,
      color: '#06B6D4',
      size: 1.2
    },
    {
      id: 'biomimetic_structures',
      name: 'Biomimetic Structures',
      lat: 48.8566,
      lng: 2.3522,
      era: 'future',
      description: 'Crochet models of coral reefs and biological forms for scientific visualization.',
      stitchType: 'Organic Form',
      curvature: -0.4,
      color: '#84CC16',
      size: 1.1
    }
  ]


  useEffect(() => {
    // Filter markers by era if specified
    const filteredMarkers = era === 'all' 
      ? culturalMarkers 
      : culturalMarkers.filter(marker => marker.era === era)
    setMarkers(filteredMarkers)

    // Auto-rotate globe
    if (isRotating && globeRef.current) {
      const interval = setInterval(() => {
        setGlobeRotation(prev => ({
          lat: prev.lat,
          lng: prev.lng + 0.2
        }))
      }, 50)
      return () => clearInterval(interval)
    }
  }, [era, isRotating])

  useEffect(() => {
    // Handle window resize and mobile detection
    const handleResize = () => {
      const width = window.innerWidth
      const isMobileDevice = width < 768
      setIsMobile(isMobileDevice)
      
      if (width < 640) {
        setGlobeSize(280)
      } else if (width < 1024) {
        setGlobeSize(400)
      } else {
        setGlobeSize(600)
      }
    }
    handleResize()
    window.addEventListener('resize', handleResize)
    return () => window.removeEventListener('resize', handleResize)
  }, [])

  const handleMarkerClick = (marker: CulturalMarker) => {
    setSelectedMarker(marker)
    if (onMarkerClick) {
      onMarkerClick(marker)
    }
    
    // Fly to marker
    if (globeRef.current) {
      globeRef.current.pointOfView(
        { lat: marker.lat, lng: marker.lng, altitude: 1.5 },
        1000
      )
    }
    setIsRotating(false)
    setTimeout(() => setIsRotating(true), 3000)
  }

  // Touch event handlers for mobile navigation
  const handleTouchStart = (e: React.TouchEvent) => {
    const touch = e.touches[0]
    setTouchStart({ x: touch.clientX, y: touch.clientY })
    setIsRotating(false) // Stop auto-rotation during touch
  }

  const handleTouchMove = (e: React.TouchEvent) => {
    if (!touchStart || !globeRef.current) return
    
    const touch = e.touches[0]
    const deltaX = touch.clientX - touchStart.x
    const deltaY = touch.clientY - touchStart.y
    
    // Rotate globe based on touch movement
    if (Math.abs(deltaX) > 10 || Math.abs(deltaY) > 10) {
      const currentRotation = globeRef.current.getPointOfView()
      globeRef.current.pointOfView({
        lat: currentRotation.lat + deltaY * 0.01,
        lng: currentRotation.lng + deltaX * 0.01,
        altitude: currentRotation.altitude
      }, 0)
      setTouchStart({ x: touch.clientX, y: touch.clientY })
    }
  }

  const handleTouchEnd = () => {
    setTouchStart(null)
    // Resume auto-rotation after a delay
    setTimeout(() => setIsRotating(true), 2000)
  }

  const getEraColor = (era: string) => {
    switch (era) {
      case 'ancient': return '#D97706'
      case 'modern': return '#059669'
      case 'future': return '#7C3AED'
      default: return '#6B7280'
    }
  }

  return (
    <div className="relative w-full h-full">
      {/* Globe Container */}
      <div
        className="relative rounded-xl overflow-hidden border"
        style={{
          borderColor: theme.colors.border,
          backgroundColor: theme.colors.background
        }}
        onTouchStart={handleTouchStart}
        onTouchMove={handleTouchMove}
        onTouchEnd={handleTouchEnd}
      >
        <Globe
          ref={globeRef}
          globeImageUrl="//unpkg.com/three-globe/example/img/earth-blue-marble.jpg"
          bumpImageUrl="//unpkg.com/three-globe/example/img/earth-topology.png"
          backgroundImageUrl="//unpkg.com/three-globe/example/img/night-sky.png"
          width={globeSize}
          height={globeSize}
          backgroundColor="rgba(0,0,0,0)"
          atmosphereColor={theme.colors.accent + '40'}
          atmosphereAltitude={0.15}
          pointsData={markers}
          pointLat="lat"
          pointLng="lng"
          pointColor="color"
          pointRadius="size"
          pointAltitude={0.01}
          pointLabel={(d: any) => `
            <div style="
              background: ${theme.colors.card};
              color: ${theme.colors.text};
              padding: 12px;
              border-radius: 8px;
              border: 1px solid ${theme.colors.border};
              max-width: 240px;
              font-family: ${theme.typography.fontFamily};
            ">
              <strong style="color: ${d.color}">${d.name}</strong><br/>
              <small>${d.stitchType} • K = ${d.curvature}</small><br/>
              <span style="font-size: 12px; color: ${theme.colors.textSecondary}">${d.description.substring(0, 80)}...</span>
            </div>
          `}
          onPointClick={(point: any) => handleMarkerClick(point)}
          pointsMerge={false}
          pointResolution={16}
          enablePointerInteraction={true}
        />

        {/* Controls */}
        <div className={`absolute ${isMobile ? 'bottom-2 left-2' : 'bottom-4 left-4'} flex flex-col gap-2`}>
          <button
            onClick={() => setIsRotating(!isRotating)}
            className={`${isMobile ? 'px-2 py-1.5 text-xs' : 'px-3 py-2 text-sm'} rounded-lg font-medium flex items-center gap-2`}
            style={{
              backgroundColor: theme.colors.card,
              color: theme.colors.text,
              border: `1px solid ${theme.colors.border}`
            }}
          >
            {isRotating ? '⏸️' : '▶️'} {isMobile ? '' : (isRotating ? 'Pause' : 'Rotate')}
          </button>
          <button
            onClick={() => {
              if (globeRef.current) {
                globeRef.current.pointOfView({ lat: 0, lng: 0, altitude: 2 }, 1000)
              }
            }}
            className={`${isMobile ? 'px-2 py-1.5 text-xs' : 'px-3 py-2 text-sm'} rounded-lg font-medium`}
            style={{
              backgroundColor: theme.colors.card,
              color: theme.colors.text,
              border: `1px solid ${theme.colors.border}`
            }}
          >
            {isMobile ? '↺' : 'Reset View'}
          </button>
        </div>

        {/* Era Legend */}
        <div className={`absolute ${isMobile ? 'top-2 right-2' : 'top-4 right-4'}`}>
          <div className={`${isMobile ? 'p-2' : 'p-3'} rounded-lg`} style={{
            backgroundColor: theme.colors.card + 'CC',
            backdropFilter: 'blur(8px)',
            border: `1px solid ${theme.colors.border}`
          }}>
            <h4 className={`${isMobile ? 'text-xs' : 'text-sm'} font-semibold mb-1`} style={{ color: theme.colors.text }}>
              {isMobile ? 'Eras' : 'Cultural Eras'}
            </h4>
            <div className="space-y-1">
              {['ancient', 'modern', 'future'].map((eraType) => (
                <div key={eraType} className="flex items-center gap-1">
                  <div
                    className={`${isMobile ? 'w-2 h-2' : 'w-3 h-3'} rounded-full`}
                    style={{ backgroundColor: getEraColor(eraType) }}
                  />
                  <span className={`${isMobile ? 'text-[10px]' : 'text-xs'} capitalize`} style={{ color: theme.colors.textSecondary }}>
                    {isMobile ? eraType.charAt(0).toUpperCase() : eraType}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Selected Marker Details */}
      <AnimatePresence>
        {selectedMarker && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 20 }}
            className={`absolute ${isMobile ? 'bottom-2 right-2 left-2' : 'bottom-4 right-4 left-4 lg:left-auto lg:w-96'}`}
          >
            <div className={`${isMobile ? 'p-3' : 'p-4'} rounded-xl border`} style={{
              backgroundColor: theme.colors.card,
              borderColor: theme.colors.border,
              boxShadow: `0 10px 30px ${theme.colors.border}20`
            }}>
              <div className="flex justify-between items-start mb-3">
                <div>
                  <h3 className={`${isMobile ? 'text-base' : 'text-lg'} font-bold`} style={{ color: selectedMarker.color }}>
                    {selectedMarker.name}
                  </h3>
                  <div className="flex items-center gap-2 mt-1">
                    <span className={`${isMobile ? 'text-[10px] px-1.5 py-0.5' : 'text-xs px-2 py-1'} rounded-full`} style={{
                      backgroundColor: getEraColor(selectedMarker.era) + '20',
                      color: getEraColor(selectedMarker.era)
                    }}>
                      {isMobile ? selectedMarker.era.charAt(0).toUpperCase() : selectedMarker.era}
                    </span>
                    <span className={`${isMobile ? 'text-[10px] px-1.5 py-0.5' : 'text-xs px-2 py-1'} rounded-full`} style={{
                      backgroundColor: theme.colors.background,
                      color: theme.colors.textSecondary
                    }}>
                      K = {selectedMarker.curvature}
                    </span>
                  </div>
                </div>
                <button
                  onClick={() => setSelectedMarker(null)}
                  className={`${isMobile ? 'w-6 h-6' : 'w-8 h-8'} rounded-full flex items-center justify-center`}
                  style={{
                    backgroundColor: theme.colors.background,
                    color: theme.colors.text,
                    border: `1px solid ${theme.colors.border}`
                  }}
                >
                  ×
                </button>
              </div>
              
              <p className={`${isMobile ? 'text-xs' : 'text-sm'} mb-3`} style={{ color: theme.colors.textSecondary }}>
                {isMobile ? `${selectedMarker.description.substring(0, 80)}...` : selectedMarker.description}
              </p>
              
              <div className={`grid ${isMobile ? 'grid-cols-2 gap-2' : 'grid-cols-2 gap-3'}`}>
                <div className={`${isMobile ? 'p-2' : 'p-3'} rounded-lg`} style={{
                  backgroundColor: theme.colors.background,
                  border: `1px solid ${theme.colors.border}`
                }}>
                  <div className={`${isMobile ? 'text-[10px]' : 'text-xs'}`} style={{ color: theme.colors.textSecondary }}>Stitch Type</div>
                  <div className={`${isMobile ? 'text-xs' : 'text-sm'} font-medium`} style={{ color: theme.colors.text }}>
                    {isMobile ? selectedMarker.stitchType.substring(0, 12) + '...' : selectedMarker.stitchType}
                  </div>
                </div>
                <div className={`${isMobile ? 'p-2' : 'p-3'} rounded-lg`} style={{
                  backgroundColor: theme.colors.background,
                  border: `1px solid ${theme.colors.border}`
                }}>
                  <div className={`${isMobile ? 'text-[10px]' : 'text-xs'}`} style={{ color: theme.colors.textSecondary }}>Curvature</div>
                  <div className={`${isMobile ? 'text-xs' : 'text-sm'} font-medium`} style={{ color: theme.colors.text }}>
                    {selectedMarker.curvature > 0 ? 'Spherical' : 'Hyperbolic'}
                  </div>
                </div>
              </div>
              
              <button
                onClick={() => {
                  // This would integrate with the pattern generator
                  console.log('Apply pattern:', selectedMarker)
                }}
                className={`w-full mt-3 ${isMobile ? 'px-3 py-2 text-xs' : 'px-4 py-2.5 text-sm'} rounded-lg font-medium flex items-center justify-center gap-2`}
                style={{
                  backgroundColor: selectedMarker.color,
                  color: theme.colors.background
                }}
              >
                {isMobile ? 'Apply Pattern' : 'Apply This Pattern Style'}
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Mobile Instructions */}
      {isMobile && !selectedMarker && (
        <div className="absolute top-2 left-2 right-2">
          <div className="p-2 rounded-lg text-center" style={{
            backgroundColor: theme.colors.card + 'CC',
            backdropFilter: 'blur(8px)',
            border: `1px solid ${theme.colors.border}`
          }}>
            <div className="text-xs" style={{ color: theme.colors.textSecondary }}>
              <span className="font-medium" style={{ color: theme.colors.text }}>Drag to rotate</span> • Tap markers for details
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default ThaliaGlobe